/*
 * This source file was generated by the Gradle 'init' task
 */
package app;

import org.junit.jupiter.api.Test;

import static org.junit.jupiter.api.Assertions.*;

class GuessTest {
    @Test
    void testGuessTooLow() {
        var game = new Guess.Game(5);
        assertEquals("low", game.guess(3));
    }
    @Test
    void testGuessTooHigh() {
        var game = new Guess.Game(5);
        assertEquals("high", game.guess(7));
    }

    @Test
    void testGuessCorrect() {
        var game = new Guess.Game(5);
        assertEquals("correct", game.guess(5));
    }
}



